# -*- coding: utf-8 -*-
"""cats_vs_dogs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WxHqH2f2NfRIAlx9puz_AgGWi-9cniF
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from PIL import Image
import time
import os
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import numpy as np
import kagglehub # Pastikan library ini diinstal (pip install kagglehub)

# ==========================================
# KONFIGURASI & AUTODOWNLOAD
# ==========================================
SEED = 42
torch.manual_seed(SEED)
BATCH_SIZE = 32
EPOCHS = 10
LR = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
IMG_SIZE = 128

print("Memeriksa dan mengunduh dataset via kagglehub...")
# Jika dataset sudah ada di cache lokal, kagglehub tidak akan mengunduh ulang
dataset_cache_path = kagglehub.dataset_download("shaunthesheep/microsoft-catsvsdogs-dataset")

# Arahkan DATA_DIR ke folder PetImages di dalam path cache
DATA_DIR = os.path.join(dataset_cache_path, "PetImages")

print(f"Mencari dataset di: {DATA_DIR}")
if not os.path.exists(DATA_DIR):
    print("ERROR: Folder 'PetImages' tidak ditemukan di direktori cache Kaggle!")
    exit()

# ==========================================
# 1. PREPROCESSING & PIPELINE
# ==========================================
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

def is_valid_file(path):
    try:
        # Coba buka gambar untuk memastikan tidak corrupt
        img = Image.open(path)
        img.verify()
        return True
    except:
        return False

print("Memuat dan memverifikasi gambar... (Ini mungkin memakan waktu beberapa menit)")
try:
    full_dataset = datasets.ImageFolder(root=DATA_DIR, transform=transform, is_valid_file=is_valid_file)
    print(f"Berhasil memuat {len(full_dataset)} gambar valid.")
except Exception as e:
    print(f"Error loading dataset: {e}")
    exit()

# Pembagian Dataset (70% Train, 15% Val, 15% Test)
train_size = int(0.7 * len(full_dataset))
val_size = int(0.15 * len(full_dataset))
test_size = len(full_dataset) - train_size - val_size
train_dataset, val_dataset, test_dataset = random_split(full_dataset, [train_size, val_size, test_size])

# Gunakan num_workers=0 untuk mencegah error multiprocessing di Windows
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

# ==========================================
# 2. ARSITEKTUR CNN
# ==========================================
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, padding=1)
        self.relu1 = nn.ReLU()
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, padding=1)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.fc1 = nn.Linear(32 * 32 * 32, 128)
        self.relu3 = nn.ReLU()
        self.fc2 = nn.Linear(128, 2)

    def forward(self, x):
        x = self.pool1(self.relu1(self.conv1(x)))
        x = self.pool2(self.relu2(self.conv2(x)))
        x = x.view(x.size(0), -1)
        x = self.relu3(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleCNN().to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=LR)

# ==========================================
# 3. TRAINING LOOP (Telah Dimodifikasi)
# ==========================================
print(f"\nMemulai Training di Device: {DEVICE}")
start_time = time.time()

# List untuk menyimpan metrik untuk keperluan plot
history_train_loss = []
history_val_loss = []

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)
    history_train_loss.append(train_loss) # Simpan train loss

    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            loss = criterion(outputs, labels)
            val_loss += loss.item()

    val_loss = val_loss / len(val_loader)
    history_val_loss.append(val_loss) # Simpan val loss

    print(f"Epoch [{epoch+1}/{EPOCHS}] | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

print(f"\nTraining selesai dalam {time.time() - start_time:.2f} detik")

# ==========================================
# 4. EVALUASI TEST SET
# ==========================================
print("\nMelakukan Evaluasi pada Test Set...")
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Akurasi Test: {100 * correct / total:.2f} %")

# 1. Plot Training Curve (Loss) - Dimodifikasi agar otomatis
plt.figure(figsize=(10, 5))
plt.plot(range(1, EPOCHS + 1), history_train_loss, label='Train Loss', marker='o')
plt.plot(range(1, EPOCHS + 1), history_val_loss, label='Validation Loss', marker='s')
plt.title('Training and Validation Loss Curve')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# 2. Confusion Matrix & Ekstrak Salah Klasifikasi
print("\nMenghasilkan Confusion Matrix dan mencari gambar salah prediksi...")
all_preds = []
all_labels = []
misclassified_images = []
misclassified_true = []
misclassified_pred = []

model.eval()
with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

        # Cari yang salah tebak
        for i in range(len(labels)):
            if predicted[i] != labels[i] and len(misclassified_images) < 3:
                # Denormalize gambar untuk ditampilkan
                img = images[i].cpu().numpy().transpose((1, 2, 0))
                img = img * 0.5 + 0.5 # Un-normalize
                misclassified_images.append(img)
                misclassified_true.append(labels[i].item())
                misclassified_pred.append(predicted[i].item())

# Print Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)
print("\n=== CONFUSION MATRIX ===")
print(cm)
print("Baris = Label Asli (Cat, Dog), Kolom = Prediksi (Cat, Dog)")

# 3. Tampilkan 3 Gambar Misklasifikasi
classes = ['Cat', 'Dog']
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
fig.suptitle('3 Contoh Misklasifikasi (Salah Tebak)', fontsize=16)
for i in range(3):
    if i < len(misclassified_images):
        axes[i].imshow(misclassified_images[i])
        axes[i].set_title(f"Asli: {classes[misclassified_true[i]]} | Prediksi: {classes[misclassified_pred[i]]}")
        axes[i].axis('off')
plt.show()